[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${RPC_SEPOLIA}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
rootstock = "${RPC_ROOTSTOCK}"
morph = "${RPC_MORPH}"



[etherscan]
sepolia={key="${ETHERSCAN_API_KEY_SEPOLIA}",chainId=11155111}
base={key="${ETHERSCAN_API_KEY_BASE}",chain=8453}
base_sepolia={key="${ETHERSCAN_API_KEY_BASE_SEPOLIA}",chain=84532}
