import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderBar } from "@/components/headerBar";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ajoo Protocol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="lg:flex flex-col w-full">
            <HeaderBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
